version: '2'

services:

    php:
        container_name: myPhp
        build: docker/php
        ports:
            - 9000:9000
        links:
            - mariadb
        volumes:
            - ./app:/var/www/html
            - ./var/logs/php:/var/www/app/var/logs

    nginx:
        container_name: myNginx
        image: nginx:alpine
        ports:
            - 8080:80
        links:
            - php
        volumes:
            - ./app:/var/www/html
            - ./var/nginx:/etc/nginx/conf.d
            - ./var/logs/nginx/:/var/log/nginx

    mariadb:
        container_name: myMariaDB
        image: mariadb:10.3.2
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - 3306:3306
        volumes:
            - ./var/mariadb:/var/lib/mysql